language: node_js
node_js:
  - "10"

sudo: required

services:
  - docker

script:
- docker run --privileged -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --budget.configPath /sitespeed.io/budget.json -n 1 https://dev.to
- yarn run lh -- --perf=100 https://dev.to
